/**
 * @constants ACTIONS
 * @description Centralized action types for the AppContext reducer.
 * Ensures type-safety and prevents typos in state transitions.
 */
export const ACTIONS = {
  SET_THEME: 'SET_THEME',
  SET_ROLE: 'SET_ROLE',
  SET_CURRENCY: 'SET_CURRENCY',
  ADD_TRANSACTION: 'ADD_TRANSACTION',
  EDIT_TRANSACTION: 'EDIT_TRANSACTION',
  DELETE_TRANSACTION: 'DELETE_TRANSACTION',
  SET_FILTERS: 'SET_FILTERS',
  RESET_DATA: 'RESET_DATA',
  ADD_TOAST: 'ADD_TOAST',
  REMOVE_TOAST: 'REMOVE_TOAST',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  CLOSE_SIDEBAR: 'CLOSE_SIDEBAR',
  TRIGGER_CELEBRATION: 'TRIGGER_CELEBRATION',
  SET_LOADING: 'SET_LOADING'
};
